name: Run Tests
on: [push]
jobs:
 TEST_PYTHON:
  runs-on: ubuntu-20.04
  steps:
   - name: Check out repository code
     uses: actions/checkout@v2
   - run: ls -la
   - name: Run Scrips to test
     run: pip3 install -r requirements.txt
   - run: python3 manage.py migrate
   - run: python3 manage.py collectstatic
   - run: python3 manage.py test
